syntax on "Turn synthax on

set nocompatible

set termguicolors

set t_Co=16

set cursorline "Show cursor highligh"

set showmode "Show mode"
 
set relativenumber "Show line number

set background=dark 

set ruler "Show file stats

set visualbell "Blink cursor instead of beep

set encoding=utf-8

set laststatus=2 "Show status line

set showmatch "Show matching parenthese

set incsearch "Search as character are entered

set hlsearch "Show mathc

set ignorecase "Search are case sensitive

syntax enable
"let g:dracula_colorterm = 0"
colorscheme solarized8_flat"
set background=dark
