#!/bin/sh

#Prevent transparancy bug
hsetroot --solid "000066"

#Set background
exec nitrogen --restore &

autostart="xcompgr blueman-applet"

for program in $autostart; do
	pidof -sx "$program" || "$program" &
done >/dev/null 2>&1
